In [105]:
library(Matrix)
library(far)
library(MASS)
library(pracma)

<h2 style="color:blue'">  More about invertible matrix </h2>

### Given: Suppose $A\in R^{nxn}$ and $A^{-1}$ exist, then the following can be said
- The columns of $A$ is the basis of $R^{n}$
- rank $A$ = n
- $Nul A=$ {$\vec{0}$}
- dim $Nul A$ = 0
- $A^{-1}A=I$
- $AA^{-1}=I$
- The Linear transformation $\vec{x} \mapsto A\vec{x}$ is one-to-one
- $A^T$ is an invertible matrix

<h2 style="color:blue'"> Rouche-Capelli Theorem </h2>

- Tells you the number of solutions in the systems of equations
- Alfredo Capelli (5 August 1855 – 28 January 1910)


### Change of basis 

Given:  $\vec{y} \notin C(A)$ , and Rank of $A$ = 2, and $\vec{y} \in R^3$

### ```Problem:```  
- Let $\hat{\vec{y}} \subset C(A)$ where $\vec{C}_1 \text{ and } \vec{C}_2$ are the basis of $C(A)$
- Find $\hat{\vec{y}}$ that minimizes $||\vec{y}-\hat{\vec{y}}||$

### Solution:
- let $C$ and $N$ be the matrix that contains the basis of $C(A)$ and $N(A^T)$
- Since: $C\vec{x}=\hat{\vec{y}} \text{   and   } C\vec{x} + N\vec{z} = \vec{y}$
- Simplify the expression
$$C^TC\vec{x} = C^T\vec{y}$$
$$\vec{x} = (C^TC)^{-1}C^T\vec{y}$$

- Then, $C(C^TC)^{-1}C^T\vec{y}=\hat{\vec{y}}$
- $C(C^TC)^{-1}C^T$ is called ```projection matrix```




### About projection matrix

$\vec{y} = P\vec{y} + B\vec{y}$ <br>
$P + B = I$


- where  $P \text{ and } B$ are the ```projection matrices``` for $C(A) \text{ and } N(A^T)$

<h2 style="color:blue'"> DOT Product  </h2>

$$\hat{\vec{y}} = P_{\vec{u}}^{\vec{y}} = \frac{\vec{y}\centerdot\vec{u}}{\vec{u}\centerdot\vec{u}}\vec{u}$$

where <br>
$\vec{y}\centerdot\vec{u} \text{ and } \vec{u}\centerdot\vec{u}$ are scalar quantity.

Projection tells you the ```length``` of the ```projected vector```, $\hat{\vec{y}}$ in terms of the vector that is ```being projected onto``` $\vec{u}$

In [44]:
# y will be projected onto u
y <- matrix(c(7,6),nrow=2)
u <- matrix(c(4,2),nrow=2)
u0 <- matrix(c(16,8),nrow=2)


### Using ```Projection matrix```

In [21]:
## using projection matrix
P <- u%*%(solve(t(u)%*%u)%*%t(u))
print(P)


     [,1] [,2]
[1,]  0.8  0.4
[2,]  0.4  0.2


In [19]:
print(P%*%y)

     [,1]
[1,]    8
[2,]    4


### Using ```Projection formula``` on to $\vec{u}$

In [37]:
print(drop((t(y)%*%u)/(t(u)%*%u))*u)

     [,1]
[1,]    8
[2,]    4


In [38]:
print(drop((t(y)%*%u)/(t(u)%*%u)))

[1] 2


### Using ```Projection formula``` on to $\vec{u}_0$

In [45]:
print(drop((t(y)%*%u0)/(t(u0)%*%u0))*u0)

     [,1]
[1,]    8
[2,]    4


In [46]:
print(drop((t(y)%*%u0)/(t(u0)%*%u0)))

[1] 0.5


### Orthonormal basis

In [82]:
mybasis <- matrix(c(1,2,3,4,5,6),nrow=3)
print(mybasis)
print(orthonormalization(mybasis))

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6
          [,1]       [,2]       [,3]
[1,] 0.2672612  0.8728716  0.4082483
[2,] 0.5345225  0.2182179 -0.8164966
[3,] 0.8017837 -0.4364358  0.4082483


In [91]:
Z <- (orthonormalization(mybasis)) # z is orthonormal basis of codomain (I called it output space)

In [78]:
A <- matrix(c(4,3,5,6,8,10,5,12,13),nrow=3, byrow=T)
print(A)

     [,1] [,2] [,3]
[1,]    4    3    5
[2,]    6    8   10
[3,]    5   12   13


In [79]:
c(Norm(A[1,]),Norm(A[2,]),Norm(A[3,])) #norm of each row vectors in A (i.e., sample)

[1]  7.071068 14.142136 18.384776

In [92]:
B <- A%*%Z
print(B)

          [,1]     [,2]          [,3]
[1,]  6.681531 1.963961  1.224745e+00
[2,] 13.897585 2.618615 -6.217249e-15
[3,] 18.173764 1.309307 -2.449490e+00


In [93]:
print(Z)

          [,1]       [,2]       [,3]
[1,] 0.2672612  0.8728716  0.4082483
[2,] 0.5345225  0.2182179 -0.8164966
[3,] 0.8017837 -0.4364358  0.4082483


### Explain the following

In [96]:
print(Z%*%B[1,])

     [,1]
[1,]    4
[2,]    3
[3,]    5


In [97]:
print(Z%*%B[2,])

     [,1]
[1,]    6
[2,]    8
[3,]   10


In [98]:
print(Z%*%B[3,])

     [,1]
[1,]    5
[2,]   12
[3,]   13


## Change of basis 1

In [99]:
b <- c(-3,-14,-17)
A <- matrix(c(1,1,2,0,3,1),nrow=3,byrow=T)

### Find $A\vec{x}=\vec{b}$ and explain the physical meaning of $\vec{x}$

## Change of basis 2

- $A$ is $R^{3x2}$ matrix and $rank(A)$ is 2.

In [114]:
a <- c(2/3,-2/3,1/3,2/3,1/3,-2/3)
A <- matrix(a,nrow=3,ncol=2,byrow=T)
print(fractions(A))


     [,1] [,2]
[1,]  2/3 -2/3
[2,]  1/3  2/3
[3,]  1/3 -2/3


### plot $C(A)$ and $E$

In [115]:
k <- rnorm(10000,5,5)
myData <- matrix(k,nrow=2,ncol=5000,byrow=T)
c_A <- A%*%myData

In [122]:
C = orthonormalization(tempC)
GS_A<- cbind(GS[,1],GS[,2])  #orthonormalized basis spanning C(A)
E <- GS_A%*%myData


- $\vec{b} \notin C(A)$ and suppose I want to flip $\vec{b}$ with respect to $C(A)$
- How would you develop the transformation matrix that flips $\vec{b}_0$?

In [121]:
b0 <- matrix(c(10,10,10),nrow=3)
B <- cbind(A,b0)
print(rref(B))

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1


- Let $D$ transformation matrix that is expressed in terms of the basis spanning $C(A)$ and $N(A^T)$
- Then, 


\begin{equation}
D = \left(
\begin{array}{cccc}
1 & 0 &  0 \\
0 & 1 &  0 \\
0 & 0 &-1 \\
\end{array}
\right)
\end{equation}

- Let $\vec{b}_{1C}$ be the flipped vector whose coordiate is expressed in terms of basis spanning $C(A)$ and $N(A^T)$
- $T\vec{b}_0=\vec{b}_{\text{1standard basis}}$ and $D\vec{b}_{0C} = \vec{b}_{1C}$
- Then, using 
 - $\vec{b}_{0C} = \text{[0 0 1]}^T$ and
 - $\vec{b}_{0} = \text{[10 10 10]}^T$ and
 - $C$ and $D$, we can get $T$
 
### Find $\vec{b}_{\text{1standard basis}}$

In [126]:
D <- matrix(c(1,0,0,0,1,0,0,0,-1), nrow=3, byrow=T)
print(D)
T <- C%*%D%*%inv(C)
print(T%*%b0)

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0   -1
          [,1]
[1,] 15.714286
[2,]  7.142857
[3,]  1.428571


## Change of basis is useful
- Developing transformation matrix
- Evaluating long term behavior of the transformation matrix
- Understanding how the initial state will evolve over time
- Determining the influence of each basis of $C(A^T)$ to the $C(A)$

## Question

- Explains what happens when you project $\vec{x}$ onto
  - basis that are not orthogonal
  - basis that are orthogonal, but not normal
  - basis that are orthonormal
and add the projected vector.