In [1]:
library(Matrix)
library(far)
library(MASS)
library(pracma)

Loading required package: nlme
far library : Modelization for Functional AutoRegressive processes

version 0.6-4 (2014-12-07)


Attaching package: ‘pracma’

The following objects are masked from ‘package:Matrix’:

    expm, lu, tril, triu



In [2]:
A = matrix(c(-3,6,-1,1,-7,1,-2,2,3,-1,2,-4,5,8,-4),nrow=3,ncol=5,byrow=TRUE)
A

[,1] [,2] [,3] [,4] [,5]
[1,] -3    6   -1   1    -7  
[2,]  1   -2    2   3    -1  
[3,]  2   -4    5   8    -4

## Column space basis

In [5]:
C_A = orth(A)
C_A

[,1]        [,2]       
[1,]  0.03354216  0.99686846
[2,] -0.36102371 -0.05472854
[3,] -0.93195322  0.05707950

## Left Nullspace basis


In [7]:
N_AT <- null(t(A))
N_AT

[,1]       
[1,] -0.07161149
[2,] -0.93094934
[3,]  0.35805744

## Basis for output space

In [9]:
OUT <- cbind(C_A, N_AT)
rref(OUT)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

## Row space basis


In [11]:
C_AT <- orth(t(A))
C_AT

[,1]       [,2]       
[1,] -0.1940942  0.29847614
[2,]  0.3881884 -0.59695228
[3,] -0.4519731  0.08359359
[4,] -0.7098521 -0.13128896
[5,]  0.3216637  0.72824124

## Nullspace basis

- Suppose $T(\vec{x}) = A\vec{x}$, then the ```kernel``` or null space of such T can be found as below.


In [12]:
N_A <- nullspace(A)
N_A

[,1]        [,2]       [,3]       
[1,]  0.04416189  0.3476413 -0.86627634
[2,]  0.41326313  0.5658536 -0.04450838
[3,]  0.85611211 -0.2202874  0.08531064
[4,] -0.25090190  0.5572485  0.32464681
[5,]  0.17715416  0.4471048  0.36730213

## Basis spanning the INPUT space

In [14]:
IN <- cbind(C_AT, N_A)
IN

[,1]       [,2]        [,3]        [,4]       [,5]       
[1,] -0.1940942  0.29847614  0.04416189  0.3476413 -0.86627634
[2,]  0.3881884 -0.59695228  0.41326313  0.5658536 -0.04450838
[3,] -0.4519731  0.08359359  0.85611211 -0.2202874  0.08531064
[4,] -0.7098521 -0.13128896 -0.25090190  0.5572485  0.32464681
[5,]  0.3216637  0.72824124  0.17715416  0.4471048  0.36730213

In [15]:
rref(IN)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    1    0    0    0   
[3,] 0    0    1    0    0   
[4,] 0    0    0    1    0   
[5,] 0    0    0    0    1

## Q1: What is the relationship between the basis spanning C(A) and N(A<sup>T</sup>)?

## Q2: What is the relationship between the basis spanning C(A<sup>T</sup>) and N(A)?

## Q3: What is the relationship between the basis spanning C(A) and C(A<sup>T</sup>)?

## Q4: What is the relationship between the basis spanning N(A) and N(A<sup>T</sup>)?

## Q5: If the basis spanning C(A) is given, can you find out the basis spanning N(A<sup>T</sup>)?

## Q6: If the basis spanning C(A<sup>T</sup>) is given, can you find out the basis spanning N(A)?