In [36]:
#install.packages('pracma')
#install.packages('far')

In [1]:
#library(Matrix)
library(far)
library(MASS)
library(pracma)

Loading required package: nlme
far library : Modelization for Functional AutoRegressive processes

version 0.6-4 (2014-12-07)



<h2 style="color:blue'"> Books used to prepare lecture notes </h2>
    
- Linear Algebra and its application by David C.Lay 4th edition 
- Linear and Nonlinear Programming by Stephen G. Nash and Ariela Sofer 
- The fundamental theorem of linear algebra, Strang, Gilbert

And a few more books and papers.

<h3 style="color:green'"> Terms you need to be already familiar with: </h3>

vector, matrix, span, subspace, linear combination 

<h1 style="color:red'"> Introduction </h1>

- This lecture start talks about concepts in linear algebra that are considered as building blocks. <br><br> 

- You need to become familiar with the concepts like the way you use different methods you invoke on different types of python object. <Br><Br>
    
- Statistics is a function of sample that tells you certain information about the sample. Since vectors and matrices contain numbers, certain attributes of the vectors and matrices can be represented by a single number or sometimes number and a vector.  
- After discussing important attribute of vectors and matrix, this lecture talks about some of the important numbers associated with vectors and matrix. These numbers tells you if certain operation can be invoked on them

    
- Objective, at the lecture three, the following sentence should make clear sense to you.
    - When you span a vector or set of vectors, you get a subspace.  When you shift a subspace by a nonzero vector, you get a hyperplane, which can be used to express the solultion set of systems of equations where the number of column is greater than the row rank and RHS is in the span of C(A). 


<h2 style="color:blue'"> Vector and their dependence </h2>

- Let $\vec{y}$, $\vec{v_1}$ and $\vec{v_2} \in R^m$ (this refers to m dimensional space where each elements is real number)

- Suppose you can express $\vec{y}$ as linear combination of $\vec{v_1}$ and $\vec{v_2}$ 

$$\vec{y} = c_1\vec{v_1} +c_2\vec{v_2}$$

- $c_1$ and $c_2$ can be viewed as weight of $\vec{v_1}$ and $\vec{v_2}$  <br><br>

- Above equestion is also saying that $\vec{y}$ can be expressed as linear combination of $\vec{v_1}$ and $\vec{v_2}$ <br><Br>
- Abvoe equation is also saying that $\vec{y} \in$ Span{$\vec{v_1}$, $\vec{v_2}$}



- I will be using ```small letters``` to denote ```vectors``` <br><br>
- ```Capital letters``` to denote ```matrix``` or ```subspace```






<h2 style="color:blue'"> Span of vectors and subspace </h2>

- When you span a vector (or vectors), you get ```subspace```.
    - Span{$\vec{v_1}...\vec{v_j}$} refers to set of all linear combination of $\vec{v_1}...\vec{v_j}$ where $\vec{v_1}...\vec{v_j} \in R^n$
    

- Properties of subspace
    - Contains $\vec{0}$
    - Closed under addition
    - Closed under multiplication

<h2 style="color:blue'"> Matrix </h2>

- The following matrix has m rows and n columns
- $A \in R^{mxn}$
\begin{equation}
A = \left(
\begin{array}{cccc}
v_{1,1} & v_{1,2} & \ldots & v_{1,n} \\
v_{2,1} & v_{2,2} & \ldots & v_{2,n} \\
\vdots & \vdots & \ddots & \vdots \\
v_{m,1} & v_{m,2} & \ldots & v_{m,n}
\end{array}
\right)
\end{equation}

<br>

<h3 style="color:green'">Row and column vectors </h3>
- I will use $\vec{v}$ and $\vec{r}$ to refer column and row vectors, respectively.
     - in indexing column vectors, I will use <b>j</b>
     - in indexing row vectors, I will use <b>i</b>
     
     
 $$A\vec{x} = \vec{b}$$ 
- $\vec{x}$ tells you the linear combination of column vectors of **A** that will give you $\vec{b}$
    
    
  $$\vec{y}A = \vec{c}$$ 
- $\vec{y}$ tells you the linear combination of row vectors of **A** that will give you $\vec{c}$

<h3 style="color:green'"> Partitioned Matrices </h3>

- $A \in R^{mxn}$
\begin{equation}
A = \left(
\begin{array}{right}
3 & 0 & -1 & 5 & 9 & -2 \\
-5 & 2 & 4 & 0 & -3 & 1 \\
-8 & -6 & 3 & 1 & 7 & -4 
\end{array}
\right)
\end{equation}
<br><br>

$$
\begin{equation}
A = \left(
\begin{array}{right}
A_{11} & A_{12} & A_{13} \\
A_{21} & A_{22} & A_{23}
\end{array}
\right)
\end{equation}$$

- $B \in R^{nxk}$
\begin{equation}
B = \left(
\begin{array}{right}
6 & 4 \\
-2 & 1 \\
-3 & 7 \\
-1 & 3 \\
5 & 2 
\end{array}
\right)
\end{equation}
<br><br>

$$
\begin{equation}
B = \left(
\begin{array}{right}
B_{1} \\
B_{2} 
\end{array}
\right)
\end{equation}$$



In [2]:
A11 <- matrix(c(3,0,-1,-5,2,4),nrow=2,byrow=T)
A12 <- matrix(c(5,9,0,3),nrow=2,byrow=T)
A13 <- matrix(c(-2,1),nrow=2,byrow=T)
A21 <- matrix(c(-8,-6,3),nrow=1,byrow=T)
A22 <- matrix(c(1,7),nrow=1,byrow=T)
A23 <- matrix(c(-4),nrow=1,byrow=T)

print(A11)
print(A12)
print(A21)
print(A22)

     [,1] [,2] [,3]
[1,]    3    0   -1
[2,]   -5    2    4
     [,1] [,2]
[1,]    5    9
[2,]    0    3
     [,1] [,2] [,3]
[1,]   -8   -6    3
     [,1] [,2]
[1,]    1    7


In [3]:
#######################################3
B1 <- matrix(c(6,4,-2,1,-3,7),nrow=3,byrow=T)
B2 <- matrix(c(-1,3,5,2),nrow=2,byrow=T)

print(B1)
print(B2)

     [,1] [,2]
[1,]    6    4
[2,]   -2    1
[3,]   -3    7
     [,1] [,2]
[1,]   -1    3
[2,]    5    2


<center>
$
\begin{equation}
AB = \left(
\begin{array}{right}
A_{11} & A_{12} \\
A_{21} & A_{22}
\end{array}
\right)
\end{equation}$
$
\begin{equation}
 \left(
\begin{array}{right}
B_{1} \\
B_{2} 
\end{array}
\right)
\end{equation}$
$
\begin{equation} 
= \left(
\begin{array}{right}
A_{11}B_1 & A_{12}B_2 \\
A_{21}B_1 & A_{22}B2
\end{array}
\right)
\end{equation}$
    
</center>

In [4]:
AB <- matrix(c(-5,4,-6,2,2,1), nrow=3,byrow=T)
print(AB)

     [,1] [,2]
[1,]   -5    4
[2,]   -6    2
[3,]    2    1


<h3 style="color:green'"> Matrix multiplication </h3>

In [5]:
r_1 <- c(1,2,4)
r_1

[1] 1 2 4

In [6]:
b <- c(2,3,4,5,6,7)
b

[1] 2 3 4 5 6 7

In [7]:
B <- matrix(b, nrow=2, ncol =3, byrow =T)
B

[,1] [,2] [,3]
[1,] 2    3    4   
[2,] 5    6    7

In [8]:
A <- matrix(c(1,2,3),nrow=1)
B%*%t(A) #matrix multiplcation, t(A) is transpose of A

[,1]
[1,] 20  
[2,] 38

In [9]:
B[1,-2] # selecting the first row without the second column

[1] 2 4

In [10]:
B[1,]

[1] 2 3 4

In [11]:
d <- matrix(c(10,20,30),nrow=1)
rbind(B,d)

[,1] [,2] [,3]
[1,]  2    3    4  
[2,]  5    6    7  
[3,] 10   20   30

In [12]:
e <- matrix(c(100,200),nrow=2)
cbind(B,e)

[,1] [,2] [,3] [,4]
[1,] 2    3    4    100 
[2,] 5    6    7    200

<h3 style="color:green'"> Vector and their dependence </h3>

- Let $c$ be nonzero real number, and $\vec{y}$ and $\vec{v_1}$ nonzero vector.

  - if $\vec{y} \notin c\vec{v_1}$ then, $\vec{y}$ and $\vec{v_1}$ are independent 



-  Let $c_1, c_2 .. c_n$ are not all nonzero real number, and $\vec{y}$ and $\vec{v_1}..\vec{v_n}$ are not all nonzero vector.

  - if $\vec{y} \notin$ Span{$\vec{v_1}, .. \vec{v_n}$}, then, $\vec{y}$ is not in the subspace spanned by $\vec{v_1}, .. \vec{v_n}$

<h1  style="color:red '"> Norm of a vector  </h1>

- Norm is extremly important concept and there number of different norms.  <br><Br>

- Norm is a function that takes $\vec{v} \in R^n$ where n is any positive number, and returns $R^1$ <Br><Br>

- The process of rescaling a vector to make its norm = 1 is called normalizing
  - divide $\vec{v}$ by its norm, ||$\vec{v}$||

<h3 style="color:green'"> Basis, Orthogonal basis, and Orthonormal basis <h3 style="color:green'">

### Basis
- Basis refers to minimum set of vectors to span a subspace or space.
    - Basis are independent of each other
    - For a given subspace or space, there are $\infty$ number of set of basis
    - Basis are not unique.
    
### Orthogonal basis
- Refers to basis that are orthogonal to each other
- $\vec{v_1}$ and $\vec{v_2}$ are orthogonal, if $\vec{v_1}\vec{v_2} = 0$
- $\vec{v}$$\vec{v}^{\perp}=0$ 

### Orthonormal basis
- basis that are 
  - orthogonal
  - < $\vec{v_i}$,$\vec{v_i}$ > = 1  for all basis

<h1 style="color:red'"> Properties of matrix </h1>

<h2 style="color:blue'"> Singular and nonsigular matrix </h2>

- For a matrix to be invertible, $A$ must satisfy the following conditions
  - $A$ is square matrix
  - All columns of <b>A</b> are independent (this is the same as saying "All the rows of $A$ are independent" since $A$ is square matrix)

- if $A^{-1}$ exists, then
    $A^{-1}A = I$ and $AA^{-1} = 1$
    
- Invertible matrix is called a <b>```nonsingular matrix```</b>
- A matrix that is not invertible is called <b>```singular matrix```</b> .

<h2 style="color:blue'"> Symmtric matrix </h2>

$$A^T = A$$

- Symmetric matrix has really nice properties and play very important role in eigenvalue analysis and pca.
- Question to think about:
  - Is symmetric matrix always sqaure?
  - Will symmetirc matrix always be invertible?

<h1 style ="color:red'"> Fundamental Four subspaces in Linear Algebra </h1>

- If I choose, the most important picture in LA, this is it.
- source: Strang, Gilbert "The fundamental theorem of linear algebra" (1993)
- Term **Input space** and **Output space** is not really widely used term.
- What I refer **Input space** is called **domain** and **Output space** is called **codomain**

<img src="subspaces.JPG" alt="drawing" width="600"/>



In [13]:
a1 <- c(-3,6,-1,1,-7)
a2 <- c(1,-2,2,3,-1)
a3 <-  c(2,-4,5,8,-4)

a <- c(a1,a2,a3)

A <- matrix(a,nrow=3,byrow=T)
A


[,1] [,2] [,3] [,4] [,5]
[1,] -3    6   -1   1    -7  
[2,]  1   -2    2   3    -1  
[3,]  2   -4    5   8    -4

In [14]:
Rank(A)

[1] 2

In [15]:
#Orthonormal basis of C(A)
orth(A)

[,1]        [,2]       
[1,]  0.03354216  0.99686846
[2,] -0.36102371 -0.05472854
[3,] -0.93195322  0.05707950

In [16]:
#Orthonormal basis of N(A)
null_s <- nullspace(A)
null_s

[,1]        [,2]       [,3]       
[1,]  0.04416189  0.3476413 -0.86627634
[2,]  0.41326313  0.5658536 -0.04450838
[3,]  0.85611211 -0.2202874  0.08531064
[4,] -0.25090190  0.5572485  0.32464681
[5,]  0.17715416  0.4471048  0.36730213

In [17]:
#Orthonormal basis of N(A)
null(A)

[,1]        [,2]       [,3]       
[1,]  0.04416189  0.3476413 -0.86627634
[2,]  0.41326313  0.5658536 -0.04450838
[3,]  0.85611211 -0.2202874  0.08531064
[4,] -0.25090190  0.5572485  0.32464681
[5,]  0.17715416  0.4471048  0.36730213

### Checking the nullspace

In [18]:
round(A%*%null_s[,1],-2)


[,1]
[1,] 0   
[2,] 0   
[3,] 0

In [19]:
round(A%*%null_s[,2],-2)


[,1]
[1,] 0   
[2,] 0   
[3,] 0

In [20]:
round(null_s[,1]%*%null_s[,2])  #basis are orthogonal

[,1]
[1,] 0

In [21]:
Norm(null_s[,1]) #and normal

[1] 1

<h2 style="color:blue'"> Rank and Nullity Theorem </h2>

### If $A$ has ```n``` columns, then rank $A$ + dim(Nul $A$) = $n$

- ```column rank``` refers to the number of basis spanning the ```column space```
- ```row rank``` refers to the number of basis spanning the ```row space```
- column rank and row rank are always the same
- ```nullity``` refers to the number of basis spanning the ```nullspace```.


### Let $A$ be invertible matrix $\in R^{nxn}$, then, we can say the following about $A$

- The columns of $A$ form a basis of $R^n$
- Col $A$ = n
- rank $A$ = n
- Nul $A$ = {$\vec{0}$}
- dim Nul $A$ = 0

<h2 style="color:blue'"> Types of equations </h2>

## Homogeneous and Inhomogeneous equations

$$A\vec{x} = \vec{b}$$  
$$A\vec{x} = \vec{0}$$

## Systems of equations can be consistent and inconsistent

### Consistent, $A\vec{x} = \vec{b}$ , there exist $\vec{x}$ for nonzero $\vec{b}$
(1) One solution case
  - $A^{-1}$ exist 
<br>

(2) Many solution case
  - $\vec{x}_p$ + $N(A)$ where $\vec{x}_p$ is a particular solution and $N(A)$ is nullspace of $A$
  
### Inconsistent, $A\vec{x} \neq \vec{b}$ , there exist no $\vec{x}$ for nonzero $\vec{b}$
  - Get the column basis of $A$
  - Develop projection matrix
  - project $\vec{b}$ onto the column space of $A$
  - You get the same result in OLS.  The coefficients from OLS is the coordinate of the basis for the $\vec{b}$ projected onto the column space of $A$

## Reduced Row Echelon Form (rref)

- rref($A$) tells you the number of independent columns of $A$.
- If $A$ has n columns and for j < n, there can be $_jC_n$ different set of independent columns

In [22]:
rref(A)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    -2   0    -1    3  
[2,] 0     0   1     2   -2  
[3,] 0     0   0     0    0

In [23]:
Rank(A) #there are two independent columns

[1] 2